### ISSUE TITLE
file

### ISSUE THREAD

**Issue by Flyzzz** [zhangshuyx/xml_parser#1]
could you tell me where is the xml file ?

**Comment by zhangshuyx** [comment]
these files can only  be used for test.



191711282@qq.com
 
From: Flyzzz
Date: 2019-02-11 10:00
To: zhangshuyx/xml_parser
CC: Subscribed
Subject: [zhangshuyx/xml_parser] file (#1)
could you tell me where is the xml file ?

**Comment by zhangshuyx** [comment]
already add xml.gz files
